
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 30 12:32:53 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 26;
  public static final int LBRACKET = 12;
  public static final int CONST = 22;
  public static final int CASE = 48;
  public static final int CONTINUE = 44;
  public static final int GREATER = 38;
  public static final int LPAREN = 14;
  public static final int SEMI = 11;
  public static final int LESS = 36;
  public static final int MINUS = 5;
  public static final int RPAREN = 15;
  public static final int AND = 33;
  public static final int LESSEQUAL = 31;
  public static final int OR = 32;
  public static final int COMMA = 19;
  public static final int CLASS = 10;
  public static final int DIV = 41;
  public static final int DIFFERENT = 51;
  public static final int PLUS = 18;
  public static final int IF = 28;
  public static final int EXCL = 34;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 27;
  public static final int RETURN = 17;
  public static final int RBRACKET = 13;
  public static final int EQUAL = 16;
  public static final int TRUE = 8;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int MOD = 42;
  public static final int NUMBER = 23;
  public static final int BREAK = 43;
  public static final int IDENT = 24;
  public static final int VOID = 21;
  public static final int SWITCH = 49;
  public static final int COL = 39;
  public static final int GREATEREQUAL = 30;
  public static final int TIMES = 4;
  public static final int SAME = 50;
  public static final int LBRACE = 3;
  public static final int ELSE = 29;
  public static final int LETTER = 25;
  public static final int READ = 45;
  public static final int POINT = 37;
  public static final int WHILE = 47;
  public static final int QUEST = 40;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 7;
  public static final int PROG = 2;
  public static final int FALSE = 9;
  public static final int DO = 46;
  public static final int PRINT = 20;
}

